In [6]:
import os
print(os.getcwd())

c:\Users\andre\Downloads\coding\gov_tech\eavs_clc\usda_ers

In [9]:
import polars as pl

timeseries = pl.read_parquet(r"..\data\cleaned\timeseries.parquet")

In [11]:
usda_ers = pl.read_csv(r"data\*.csv")
usda_ers = usda_ers.filter(pl.col("Attribute").str.contains(r"\d{4}$"))

usda_ers = usda_ers.with_columns(
    (pl.col("Attribute").str.slice(0, length = pl.col("Attribute").str.len_chars() - 5).str.to_lowercase()).alias("attribute"),
    (pl.col("Attribute").str.tail(4).cast(pl.Int16).alias("year")),
    (pl.col("FIPS_Code")).cast(pl.String).alias("fips_code"),
)

usda_ers = usda_ers.rename({"Value": "value"})

usda_ers = usda_ers.drop(["FIPS_Code", "State", "Area_Name", "Attribute"])

timeseries_usda_ers_subset = timeseries.select("fips_code", "year", "jurisdiction_name").join(usda_ers, how = "left", on = ["fips_code", "year"])

timeseries_usda_ers_subset = timeseries_usda_ers_subset.pivot(
    values = "value",
    index = ["fips_code", "year", "jurisdiction_name"],
    columns = "attribute",
    aggregate_function = "first"
)

timeseries_usda_ers_subset = timeseries_usda_ers_subset.drop(["null"])

timeseries_usda_ers_subset.write_parquet("timeseries_usda_ers_subset.parquet")

timeseries_usda_ers_subset

C:\Users\andre\AppData\Local\Temp\ipykernel_25336\3185605660.py:16: DeprecationWarning: The argument `columns` for `DataFrame.pivot` is deprecated. It has been renamed to `on`.
  timeseries_usda_ers_subset = timeseries_usda_ers_subset.pivot(

shape: (57_646, 27)
┌───────────┬──────┬────────────┬────────────┬───┬────────────┬───────────┬────────────┬───────────┐
│ fips_code ┆ year ┆ jurisdicti ┆ civilian_l ┆ … ┆ r_domestic ┆ r_net_mig ┆ median_hou ┆ med_hh_in │
│ ---       ┆ ---  ┆ on_name    ┆ abor_force ┆   ┆ _mig       ┆ ---       ┆ sehold_inc ┆ come_perc │
│ str       ┆ i64  ┆ ---        ┆ ---        ┆   ┆ ---        ┆ f64       ┆ ome        ┆ ent_of_st │
│           ┆      ┆ str        ┆ f64        ┆   ┆ f64        ┆           ┆ ---        ┆ ate…      │
│           ┆      ┆            ┆            ┆   ┆            ┆           ┆ f64        ┆ ---       │
│           ┆      ┆            ┆            ┆   ┆            ┆           ┆            ┆ f64       │
╞═══════════╪══════╪════════════╪════════════╪═══╪════════════╪═══════════╪════════════╪═══════════╡
│ 02000     ┆ 2004 ┆ ALASKA     ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│ 02000     ┆ 2006 ┆ ALASKA     ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│ 02000     ┆ 2008 ┆ ALASKA     ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│ 02000     ┆ 2010 ┆ ALASKA     ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│ 02000     ┆ 2012 ┆ ALASKA     ┆ null       ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│ …         ┆ …    ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …          ┆ …         │
│ 56045     ┆ 2014 ┆ WESTON     ┆ 3925.0     ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│           ┆      ┆ COUNTY     ┆            ┆   ┆            ┆           ┆            ┆           │
│ 56045     ┆ 2016 ┆ WESTON     ┆ 3960.0     ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│           ┆      ┆ COUNTY     ┆            ┆   ┆            ┆           ┆            ┆           │
│ 56045     ┆ 2018 ┆ WESTON     ┆ 3784.0     ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│           ┆      ┆ COUNTY     ┆            ┆   ┆            ┆           ┆            ┆           │
│ 56045     ┆ 2020 ┆ WESTON     ┆ 3786.0     ┆ … ┆ null       ┆ null      ┆ null       ┆ null      │
│           ┆      ┆ COUNTY     ┆            ┆   ┆            ┆           ┆            ┆           │
│ 56045     ┆ 2022 ┆ WESTON     ┆ 3823.0     ┆ … ┆ 22.9       ┆ 22.3      ┆ 67677.0    ┆ 95.0      │
│           ┆      ┆ COUNTY     ┆            ┆   ┆            ┆           ┆            ┆           │
└───────────┴──────┴────────────┴────────────┴───┴────────────┴───────────┴────────────┴───────────┘

In [12]:
timeseries_with_usda_ers = timeseries.join(usda_ers, how = "left", on = ["fips_code", "year"])

timeseries_with_usda_ers = timeseries_with_usda_ers.pivot(
    values = "value",
    index = [i for i in timeseries.columns if i != "value"],
    columns = "attribute",
    aggregate_function = "first"
)

timeseries_with_usda_ers = timeseries_with_usda_ers.drop(["null"])

timeseries_with_usda_ers.write_parquet("timeseries_with_usda_ers.parquet")

timeseries_with_usda_ers

C:\Users\andre\AppData\Local\Temp\ipykernel_25336\3965995239.py:3: DeprecationWarning: The argument `columns` for `DataFrame.pivot` is deprecated. It has been renamed to `on`.
  timeseries_with_usda_ers = timeseries_with_usda_ers.pivot(

shape: (57_667, 504)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ fips_code ┆ state   ┆ state_abbr ┆ jurisdict ┆ … ┆ r_domesti ┆ r_net_mig ┆ median_ho ┆ med_hh_in │
│ ---       ┆ ---     ┆ ---        ┆ ion_name  ┆   ┆ c_mig     ┆ ---       ┆ usehold_i ┆ come_perc │
│ str       ┆ str     ┆ str        ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ncome     ┆ ent_of_st │
│           ┆         ┆            ┆ str       ┆   ┆ f64       ┆           ┆ ---       ┆ ate…      │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆ f64       ┆ ---       │
│           ┆         ┆            ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 02000     ┆ ALASKA  ┆ AK         ┆ ALASKA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 02000     ┆ ALASKA  ┆ AK         ┆ ALASKA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 02000     ┆ ALASKA  ┆ AK         ┆ ALASKA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 02000     ┆ ALASKA  ┆ AK         ┆ ALASKA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 02000     ┆ ALASKA  ┆ AK         ┆ ALASKA    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …         ┆ …       ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 56045     ┆ WYOMING ┆ WY         ┆ WESTON    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│           ┆         ┆            ┆ COUNTY    ┆   ┆           ┆           ┆           ┆           │
│ 56045     ┆ WYOMING ┆ WY         ┆ WESTON    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│           ┆         ┆            ┆ COUNTY    ┆   ┆           ┆           ┆           ┆           │
│ 56045     ┆ WYOMING ┆ WY         ┆ WESTON    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│           ┆         ┆            ┆ COUNTY    ┆   ┆           ┆           ┆           ┆           │
│ 56045     ┆ WYOMING ┆ WY         ┆ WESTON    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│           ┆         ┆            ┆ COUNTY    ┆   ┆           ┆           ┆           ┆           │
│ 56045     ┆ WYOMING ┆ WY         ┆ WESTON    ┆ … ┆ 22.9      ┆ 22.3      ┆ 67677.0   ┆ 95.0      │
│           ┆         ┆            ┆ COUNTY    ┆   ┆           ┆           ┆           ┆           │
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘